<a href="https://colab.research.google.com/github/sarathkurapati/ml-dl-notebooks/blob/main/Bank_marketing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [212]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [213]:
df=pd.read_csv("/content/Bank Marketing.csv")

In [214]:
df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
0,1,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,1
1,2,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,1
2,3,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,1
3,4,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,1
4,5,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,1

In [215]:
df.V2.unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [216]:
df.V3.unique()

array(['married', 'single', 'divorced'], dtype=object)

In [217]:
df.V4.unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [218]:
df.V7.unique()

array(['yes', 'no'], dtype=object)

In [219]:
df.V9.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [220]:
df.V16.unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

In [221]:
df.Class.unique()

array([1, 2])

**DATA PREPROCESSING**

DROPPING UNNECESSARY COLUMNS

In [222]:
df.drop(columns="id",axis=1,inplace=True)

In [223]:
df.head(2)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,1
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,1

CONVERTING CATEGORICAL INTO NUMERICAL (LABEL ENCODING)

In [224]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
categorical_cols=["V2"	,"V3",	"V4",	"V5",	"V7",	"V8",	"V9","V11","V16"]
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [225]:
df.head(2)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,1
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,1

CHECKING NULL VALUES

In [226]:
df.isnull().sum()

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
V11      0
V12      0
V13      0
V14      0
V15      0
V16      0
Class    0
dtype: int64

In [227]:
df.shape

(45211, 17)

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      45211 non-null  int64
 1   V2      45211 non-null  int64
 2   V3      45211 non-null  int64
 3   V4      45211 non-null  int64
 4   V5      45211 non-null  int64
 5   V6      45211 non-null  int64
 6   V7      45211 non-null  int64
 7   V8      45211 non-null  int64
 8   V9      45211 non-null  int64
 9   V10     45211 non-null  int64
 10  V11     45211 non-null  int64
 11  V12     45211 non-null  int64
 12  V13     45211 non-null  int64
 13  V14     45211 non-null  int64
 14  V15     45211 non-null  int64
 15  V16     45211 non-null  int64
 16  Class   45211 non-null  int64
dtypes: int64(17)
memory usage: 5.9 MB

In [229]:
df.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,4.339762,1.167725,1.224813,0.018027,1362.272058,0.555838,0.160226,0.640242,15.806419,5.523014,258.163080,2.763841,40.197828,0.580323,2.559974,1.116985
std,10.618762,3.272657,0.608230,0.747997,0.133049,3044.765829,0.496878,0.366820,0.897951,8.322476,3.006911,257.527812,3.098021,100.128746,2.303441,0.989059,0.321406
min,18.000000,0.000000,0.000000,0.000000,0.000000,-8019.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,-1.000000,0.000000,0.000000,1.000000
25%,33.000000,1.000000,1.000000,1.000000,0.000000,72.000000,0.000000,0.000000,0.000000,8.000000,3.000000,103.000000,1.000000,-1.000000,0.000000,3.000000,1.000000
50%,39.000000,4.000000,1.000000,1.000000,0.000000,448.000000,1.000000,0.000000,0.000000,16.000000,6.000000,180.000000,2.000000,-1.000000,0.000000,3.000000,1.000000
75%,48.000000,7.000000,2.000000,2.000000,0.000000,1428.000000,1.000000,0.000000,2.000000,21.000000,8.000000,319.000000,3.000000,-1.000000,0.000000,3.000000,1.000000
max,95.000000,11.000000,2.000000,3.000000,1.000000,102127.000000,1.000000,1.000000,2.000000,31.000000,11.000000,4918.000000,63.000000,871.000000,275.000000,3.000000,2.000000

In [230]:
df.corr()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,Class
V1,1.000000,-0.021868,-0.403240,-0.106807,-0.017879,0.097783,-0.185513,-0.015655,0.026221,-0.009120,-0.042357,-0.004648,0.004760,-0.023758,0.001288,0.007367,0.025155
V2,-0.021868,1.000000,0.062045,0.166707,-0.006853,0.018232,-0.125363,-0.033004,-0.082063,0.022856,-0.092870,0.004744,0.006839,-0.024455,-0.000911,0.011010,0.040438
V3,-0.403240,0.062045,1.000000,0.108576,-0.007023,0.002122,-0.016096,-0.046893,-0.039201,-0.005261,-0.006991,0.011852,-0.008994,0.019172,0.014973,-0.016850,0.045588
V4,-0.106807,0.166707,0.108576,1.000000,-0.010718,0.064514,-0.090790,-0.048574,-0.110928,0.022671,-0.057304,0.001935,0.006255,0.000052,0.017570,-0.019361,0.066241
V5,-0.017879,-0.006853,-0.007023,-0.010718,1.000000,-0.066745,-0.006025,0.077234,0.015404,0.009424,0.011486,-0.010021,0.016822,-0.029979,-0.018329,0.034898,-0.022419
V6,0.097783,0.018232,0.002122,0.064514,-0.066745,1.000000,-0.068768,-0.084350,-0.027273,0.004503,0.019777,0.021560,-0.014578,0.003435,0.016674,-0.020967,0.052838
V7,-0.185513,-0.125363,-0.016096,-0.090790,-0.006025,-0.068768,1.000000,0.041323,0.188123,-0.027982,0.271481,0.005075,-0.023599,0.124178,0.037076,-0.099971,-0.139173
V8,-0.015655,-0.033004,-0.046893,-0.048574,0.077234,-0.084350,0.041323,1.000000,-0.010873,0.011370,0.022145,-0.012412,0.009980,-0.022754,-0.011043,0.015458,-0.068185
V9,0.026221,-0.082063,-0.039201,-0.110928,0.015404,-0.027273,0.188123,-0.010873,1.000000,-0.027936,0.361145,-0.020839,0.019614,-0.244816,-0.147811,0.272214,-0.148395
V10,-0.009120,0.022856,-0.005261,0.022671,0.009424,0.004503,-0.027982,0.011370,-0.027936,1.000000,-0.006028,-0.030206,0.162490,-0.093044,-0.051710,0.083460,-0.028348
V11,-0.042357,-0.092870,-0.006991,-0.057304,0.011486,0.019777,0.271481,0.022145,0.361145,-0.006028,1.000000,0.006314,-0.110031,0.033065,0.022727,-0.033038,-0.024471
V12,-0.004648,0.004744,0.011852,0.001935,-0.010021,0.021560,0.005075,-0.012412,-0.020839,-0.030206,0.006314,1.000000,-0.084570,-0.001565,0.001203,0.010925,0.394521
V13,0.004760,0.006839,-0.008994,0.006255,0.016822,-0.014578,-0.023599,0.009980,0.019614,0.162490,-0.110031,-0.084570,1.000000,-0.088628,-0.032855,0.101588,-0.073172
V14,-0.023758,-0.024455,0.019172,0.000052,-0.029979,0.003435,0.124178,-0.022754,-0.244816,-0.093044,0.033065,-0.001565,-0.088628,1.000000,0.454820,-0.858362,0.103621
V15,0.001288,-0.000911,0.014973,0.017570,-0.018329,0.016674,0.037076,-0.011043,-0.147811,-0.051710,0.022727,0.001203,-0.032855,0.454820,1.000000,-0.489752,0.093236
V16,0.007367,0.011010,-0.016850,-0.019361,0.034898,-0.020967,-0.099971,0.015458,0.272214,0.083460,-0.033038,0.010925,0.101588,-0.858362,-0.489752,1.000000,-0.077840
Class,0.025155,0.040438,0.045588,0.066241,-0.022419,0.052838,-0.139173,-0.068185,-0.148395,-0.028348,-0.024471,0.394521,-0.073172,0.103621,0.093236,-0.077840,1.000000

CHOOSING THE DEPENDENT AND INDEPENDENT ATTRIBUTES

In [231]:
x=df.drop(columns="Class",axis=1)
x.head()

   V1  V2  V3  V4  V5    V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
0  58   4   1   2   0  2143   1   0   2    5    8  261    1   -1    0    3
1  44   9   2   1   0    29   1   0   2    5    8  151    1   -1    0    3
2  33   2   1   1   0     2   1   1   2    5    8   76    1   -1    0    3
3  47   1   1   3   0  1506   1   0   2    5    8   92    1   -1    0    3
4  33  11   2   3   0     1   0   0   2    5    8  198    1   -1    0    3

In [232]:
y=df[["Class"]]
y.head()

   Class
0      1
1      1
2      1
3      1
4      1

In [233]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [234]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((31647, 16), (13564, 16), (31647, 1), (13564, 1))

ANN **CLASSIFICATION**

In [235]:
#ANN CLASSIFICATION
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [236]:
model=Sequential()
#input to model
model.add(Dense(16,activation="relu"))
#adding hidden layers
model.add(Dense(36,activation="relu"))
model.add(Dense(16,activation="relu"))
#output layer to the model
model.add(Dense(1,activation="sigmoid"))

In [237]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [238]:
model.fit(x_train,y_train,epochs=10,batch_size=20,validation_data=(x_test,y_test))

Epoch 1/10
1583/1583 [==============================] - 7s 3ms/step - loss: -4368039.0000 - accuracy: 0.8833 - val_loss: -17353918.0000 - val_accuracy: 0.8824
Epoch 2/10
1583/1583 [==============================] - 4s 3ms/step - loss: -82054320.0000 - accuracy: 0.8833 - val_loss: -182009312.0000 - val_accuracy: 0.8824
Epoch 3/10
1583/1583 [==============================] - 4s 3ms/step - loss: -456838656.0000 - accuracy: 0.8833 - val_loss: -739950016.0000 - val_accuracy: 0.8824
Epoch 4/10
1583/1583 [==============================] - 6s 4ms/step - loss: -1342367744.0000 - accuracy: 0.8833 - val_loss: -1862773120.0000 - val_accuracy: 0.8824
Epoch 5/10
1583/1583 [==============================] - 5s 3ms/step - loss: -2954159104.0000 - accuracy: 0.8833 - val_loss: -3817730048.0000 - val_accuracy: 0.8824
Epoch 6/10
1583/1583 [==============================] - 6s 4ms/step - loss: -5736543744.0000 - accuracy: 0.8833 - val_loss: -7035153408.0000 - val_accuracy: 0.8824
Epoch 7/10
1583/1583 [==============================] - 4s 3ms/step - loss: -9749667840.0000 - accuracy: 0.8833 - val_loss: -11405607936.0000 - val_accuracy: 0.8824
Epoch 8/10
1583/1583 [==============================] - 5s 3ms/step - loss: -15367592960.0000 - accuracy: 0.8833 - val_loss: -17604032512.0000 - val_accuracy: 0.8824
Epoch 9/10
1583/1583 [==============================] - 5s 3ms/step - loss: -23289516032.0000 - accuracy: 0.8833 - val_loss: -25975138304.0000 - val_accuracy: 0.8824
Epoch 10/10
1583/1583 [==============================] - 5s 3ms/step - loss: -33329362944.0000 - accuracy: 0.8833 - val_loss: -36483592192.0000 - val_accuracy: 0.8824

In [239]:
y_pred=model.predict(x_test)

424/424 [==============================] - 1s 1ms/step

TESTING WITH ANN REGRESSOR

In [240]:
model.predict([[58	,4	,1,	2,	0	,2143,	1,	0	,2	,5	,8	,261	,1	,-1,	0	,3]])

1/1 [==============================] - 0s 42ms/step

array([[1.]], dtype=float32)

NAIVE BAYES

In [241]:
#NAIVE_BAYES
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# Create a Naive Bayes model
nav_model= GaussianNB()
# Train the model
nav_model.fit(x_train, y_train)
# Make predictions on the test set
y_pred3 = nav_model.predict(x_test)
# Calculate the accuracy of the model
acc_3 = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_3)

Accuracy: 0.8824093187850192

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

DECISION TREE

In [242]:
#DECISION_TREE
from sklearn.tree import DecisionTreeClassifier
# Create a decision tree model
dec_model = DecisionTreeClassifier()
# Train the model
dec_model.fit(x_train, y_train)
# Make predictions on the test set
y_pred4 = dec_model.predict(x_test)
#Calculate the accuracy of the model
acc_4 = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_4)

Accuracy: 0.8824093187850192

SUPPORT VECTOR MACHINE

In [243]:
#SVM
from sklearn.svm import SVC
# Create a decision tree model
svm_model = SVC()
# Train the model
svm_model.fit(x_train, y_train)
# Make predictions on the test set
y_pred5 = model.predict(x_test)
# Calculate the accuracy of the model
acc_5 = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_5)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

424/424 [==============================] - 1s 2ms/step
Accuracy: 0.8824093187850192

ADA BOOST CLASSIFIER

In [244]:
#ADA BOOST CLASSIFIER
from sklearn.ensemble import AdaBoostClassifier
# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
# Train Adaboost Classifer
ad_model = abc.fit(x_train, y_train)
#Predict the response for test dataset
y_pred6 = ad_model.predict(x_test)
# Calculate the accuracy of the model
acc_6 = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_6)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy: 0.8824093187850192

RANDOM FOREST

In [247]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
# Create a decision tree model
random_model = RandomForestClassifier()
# Train the model
random_model.fit(x_train, y_train)
# Make predictions on the test set
y_pred7 = random_model.predict(x_test)
# Calculate the accuracy of the model
acc_7 = accuracy_score(y_test, y_pred)
print("Accuracy:", acc_7)

<ipython-input-247-361ac2848913>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_model.fit(x_train, y_train)

Accuracy: 0.8757741079327632

K NEIGHBORS CLASSIFIER

In [246]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
acc_1=accuracy_score(y_pred,y_test)
acc_1

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

0.8757741079327632