<a href="https://colab.research.google.com/github/sarathkurapati/ml-dl-notebooks/blob/main/BCWdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pandas as pd
import seaborn as sns

In [ ]:
df=pd.read_csv("BCWdata.csv")

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=["Unnamed: 32","id"],axis=1,inplace=True)

In [ ]:
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
df.diagnosis.unique()

array(['M', 'B'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.diagnosis=le.fit_transform(df.diagnosis)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
x=df.drop(columns="diagnosis",axis=1)
y=df.diagnosis

In [ ]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#initializing the object
classification_model=Sequential()

In [ ]:
#building an ann model for classification
#input layer  
classification_model.add(Dense(30,activation="relu"))
#hidden layers------->
classification_model.add(Dense(64,activation="relu"))
classification_model.add(Dense(36,activation="relu"))
classification_model.add(Dense(16,activation="relu"))
classification_model.add(Dense(10,activation="relu"))
#output layer
classification_model.add(Dense(1,activation="sigmoid"))

In [ ]:
classification_model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
classification_model.fit(x_train,y_train,batch_size=8,epochs=400,validation_data=(x_test,y_test))

Epoch 1/400
57/57 [==============================] - 2s 8ms/step - loss: 3.0907 - accuracy: 0.5802 - val_loss: 0.4987 - val_accuracy: 0.8596
Epoch 2/400
57/57 [==============================] - 0s 4ms/step - loss: 0.4267 - accuracy: 0.8879 - val_loss: 0.4090 - val_accuracy: 0.8596
Epoch 3/400
57/57 [==============================] - 0s 3ms/step - loss: 0.3753 - accuracy: 0.8703 - val_loss: 0.3275 - val_accuracy: 0.8860
Epoch 4/400
57/57 [==============================] - 0s 3ms/step - loss: 0.3214 - accuracy: 0.8857 - val_loss: 0.3797 - val_accuracy: 0.8070
Epoch 5/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2876 - accuracy: 0.9011 - val_loss: 0.2826 - val_accuracy: 0.9035
Epoch 6/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2748 - accuracy: 0.8945 - val_loss: 0.2599 - val_accuracy: 0.9211
Epoch 7/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2703 - accuracy: 0.9055 - val_loss: 0.2547 - val_accuracy: 0.9211
Epoch 8/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2879 - accuracy: 0.8967 - val_loss: 0.3214 - val_accuracy: 0.8509
Epoch 9/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2780 - accuracy: 0.9077 - val_loss: 0.2400 - val_accuracy: 0.9386
Epoch 10/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2632 - accuracy: 0.9033 - val_loss: 0.2780 - val_accuracy: 0.8860
Epoch 11/400
57/57 [==============================] - 0s 5ms/step - loss: 0.3729 - accuracy: 0.8527 - val_loss: 0.3196 - val_accuracy: 0.8772
Epoch 12/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2835 - accuracy: 0.8747 - val_loss: 0.3785 - val_accuracy: 0.8684
Epoch 13/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2348 - accuracy: 0.9121 - val_loss: 0.2536 - val_accuracy: 0.9123
Epoch 14/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2124 - accuracy: 0.9275 - val_loss: 0.2233 - val_accuracy: 0.9035
Epoch 15/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2907 - accuracy: 0.8791 - val_loss: 0.2525 - val_accuracy: 0.8772
Epoch 16/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2277 - accuracy: 0.9055 - val_loss: 0.2200 - val_accuracy: 0.9474
Epoch 17/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2257 - accuracy: 0.9121 - val_loss: 0.2962 - val_accuracy: 0.8596
Epoch 18/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2888 - accuracy: 0.8857 - val_loss: 0.4256 - val_accuracy: 0.8158
Epoch 19/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2026 - accuracy: 0.9253 - val_loss: 0.2211 - val_accuracy: 0.9035
Epoch 20/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2298 - accuracy: 0.9055 - val_loss: 0.2780 - val_accuracy: 0.8947
Epoch 21/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2594 - accuracy: 0.9033 - val_loss: 0.3390 - val_accuracy: 0.8947
Epoch 22/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2171 - accuracy: 0.9099 - val_loss: 0.2272 - val_accuracy: 0.9386
Epoch 23/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2321 - accuracy: 0.9055 - val_loss: 0.2553 - val_accuracy: 0.8860
Epoch 24/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2213 - accuracy: 0.9143 - val_loss: 0.2201 - val_accuracy: 0.9474
Epoch 25/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2195 - accuracy: 0.9077 - val_loss: 0.2055 - val_accuracy: 0.9386
Epoch 26/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2588 - accuracy: 0.8901 - val_loss: 0.3269 - val_accuracy: 0.8772
Epoch 27/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2958 - accuracy: 0.8857 - val_loss: 0.6853 - val_accuracy: 0.6754
Epoch 28/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2685 - accuracy: 0.8879 - val_loss: 0.2332 - val_accuracy: 0.9211
Epoch 29/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2319 - accuracy: 0.9033 - val_loss: 0.2442 - val_accuracy: 0.8772
Epoch 30/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2015 - accuracy: 0.9231 - val_loss: 0.3065 - val_accuracy: 0.9035
Epoch 31/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2033 - accuracy: 0.9209 - val_loss: 0.3075 - val_accuracy: 0.9035
Epoch 32/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2023 - accuracy: 0.9187 - val_loss: 0.2029 - val_accuracy: 0.9298
Epoch 33/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2026 - accuracy: 0.9231 - val_loss: 0.2047 - val_accuracy: 0.9474
Epoch 34/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1824 - accuracy: 0.9275 - val_loss: 0.5273 - val_accuracy: 0.8421
Epoch 35/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2535 - accuracy: 0.9077 - val_loss: 0.2161 - val_accuracy: 0.9123
Epoch 36/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2046 - accuracy: 0.9231 - val_loss: 0.2047 - val_accuracy: 0.9474
Epoch 37/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1959 - accuracy: 0.9209 - val_loss: 0.2409 - val_accuracy: 0.8772
Epoch 38/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2006 - accuracy: 0.9011 - val_loss: 0.2163 - val_accuracy: 0.8947
Epoch 39/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1957 - accuracy: 0.9033 - val_loss: 0.2861 - val_accuracy: 0.9035
Epoch 40/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2133 - accuracy: 0.9143 - val_loss: 0.2159 - val_accuracy: 0.8947
Epoch 41/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1786 - accuracy: 0.9429 - val_loss: 0.3455 - val_accuracy: 0.8333
Epoch 42/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2251 - accuracy: 0.9077 - val_loss: 0.2079 - val_accuracy: 0.9386
Epoch 43/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1874 - accuracy: 0.9187 - val_loss: 0.2798 - val_accuracy: 0.8684
Epoch 44/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2112 - accuracy: 0.9121 - val_loss: 0.2371 - val_accuracy: 0.8860
Epoch 45/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1883 - accuracy: 0.9231 - val_loss: 0.2342 - val_accuracy: 0.8772
Epoch 46/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2265 - accuracy: 0.9121 - val_loss: 0.2072 - val_accuracy: 0.9123
Epoch 47/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1774 - accuracy: 0.9297 - val_loss: 0.2268 - val_accuracy: 0.9474
Epoch 48/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2207 - accuracy: 0.9187 - val_loss: 0.2538 - val_accuracy: 0.8772
Epoch 49/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1960 - accuracy: 0.9231 - val_loss: 0.2649 - val_accuracy: 0.8684
Epoch 50/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1932 - accuracy: 0.9451 - val_loss: 0.1984 - val_accuracy: 0.9211
Epoch 51/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1903 - accuracy: 0.9253 - val_loss: 0.2180 - val_accuracy: 0.8860
Epoch 52/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1867 - accuracy: 0.9187 - val_loss: 0.2117 - val_accuracy: 0.8860
Epoch 53/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1792 - accuracy: 0.9209 - val_loss: 0.4688 - val_accuracy: 0.9035
Epoch 54/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1986 - accuracy: 0.9231 - val_loss: 0.1834 - val_accuracy: 0.9561
Epoch 55/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1991 - accuracy: 0.9209 - val_loss: 0.2798 - val_accuracy: 0.8596
Epoch 56/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2174 - accuracy: 0.9077 - val_loss: 0.2398 - val_accuracy: 0.8684
Epoch 57/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2160 - accuracy: 0.9187 - val_loss: 0.1948 - val_accuracy: 0.9386
Epoch 58/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1920 - accuracy: 0.9297 - val_loss: 0.1819 - val_accuracy: 0.9561
Epoch 59/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2252 - accuracy: 0.9121 - val_loss: 0.2686 - val_accuracy: 0.9123
Epoch 60/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2131 - accuracy: 0.9165 - val_loss: 0.1948 - val_accuracy: 0.9298
Epoch 61/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1872 - accuracy: 0.9297 - val_loss: 0.1812 - val_accuracy: 0.9386
Epoch 62/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1902 - accuracy: 0.9187 - val_loss: 0.2113 - val_accuracy: 0.9386
Epoch 63/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1830 - accuracy: 0.9275 - val_loss: 0.2244 - val_accuracy: 0.8684
Epoch 64/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1965 - accuracy: 0.9099 - val_loss: 0.2354 - val_accuracy: 0.9474
Epoch 65/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2081 - accuracy: 0.9187 - val_loss: 0.2593 - val_accuracy: 0.8596
Epoch 66/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2393 - accuracy: 0.8945 - val_loss: 0.1693 - val_accuracy: 0.9386
Epoch 67/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1740 - accuracy: 0.9297 - val_loss: 0.1737 - val_accuracy: 0.9474
Epoch 68/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1871 - accuracy: 0.9253 - val_loss: 0.1976 - val_accuracy: 0.9386
Epoch 69/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1913 - accuracy: 0.9187 - val_loss: 0.1806 - val_accuracy: 0.9035
Epoch 70/400
57/57 [==============================] - 0s 6ms/step - loss: 0.1777 - accuracy: 0.9253 - val_loss: 0.1832 - val_accuracy: 0.9386
Epoch 71/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1766 - accuracy: 0.9231 - val_loss: 0.1682 - val_accuracy: 0.9561
Epoch 72/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1748 - accuracy: 0.9319 - val_loss: 0.1598 - val_accuracy: 0.9474
Epoch 73/400
57/57 [==============================] - 0s 6ms/step - loss: 0.2644 - accuracy: 0.8879 - val_loss: 0.1825 - val_accuracy: 0.9386
Epoch 74/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1659 - accuracy: 0.9385 - val_loss: 0.1748 - val_accuracy: 0.9474
Epoch 75/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1738 - accuracy: 0.9319 - val_loss: 0.1756 - val_accuracy: 0.9561
Epoch 76/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1557 - accuracy: 0.9363 - val_loss: 0.1908 - val_accuracy: 0.9123
Epoch 77/400
57/57 [==============================] - 0s 5ms/step - loss: 0.2390 - accuracy: 0.9187 - val_loss: 0.3423 - val_accuracy: 0.8246
Epoch 78/400
57/57 [==============================] - 0s 6ms/step - loss: 0.2068 - accuracy: 0.9253 - val_loss: 0.2208 - val_accuracy: 0.8684
Epoch 79/400
57/57 [==============================] - 0s 4ms/step - loss: 0.2001 - accuracy: 0.9231 - val_loss: 0.2252 - val_accuracy: 0.9035
Epoch 80/400
57/57 [==============================] - 0s 8ms/step - loss: 0.1775 - accuracy: 0.9319 - val_loss: 0.2306 - val_accuracy: 0.9211
Epoch 81/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1620 - accuracy: 0.9209 - val_loss: 0.1639 - val_accuracy: 0.9561
Epoch 82/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1676 - accuracy: 0.9275 - val_loss: 0.1821 - val_accuracy: 0.9386
Epoch 83/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1633 - accuracy: 0.9341 - val_loss: 0.1945 - val_accuracy: 0.8860
Epoch 84/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1830 - accuracy: 0.9319 - val_loss: 0.2046 - val_accuracy: 0.9474
Epoch 85/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1742 - accuracy: 0.9253 - val_loss: 0.2247 - val_accuracy: 0.9386
Epoch 86/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1780 - accuracy: 0.9187 - val_loss: 0.2698 - val_accuracy: 0.8509
Epoch 87/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1934 - accuracy: 0.9253 - val_loss: 0.1819 - val_accuracy: 0.9386
Epoch 88/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1773 - accuracy: 0.9363 - val_loss: 0.1668 - val_accuracy: 0.9561
Epoch 89/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1630 - accuracy: 0.9275 - val_loss: 0.1507 - val_accuracy: 0.9561
Epoch 90/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1459 - accuracy: 0.9429 - val_loss: 0.1814 - val_accuracy: 0.9386
Epoch 91/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1667 - accuracy: 0.9385 - val_loss: 0.2053 - val_accuracy: 0.9386
Epoch 92/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1644 - accuracy: 0.9319 - val_loss: 0.2134 - val_accuracy: 0.9386
Epoch 93/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1627 - accuracy: 0.9319 - val_loss: 0.1499 - val_accuracy: 0.9561
Epoch 94/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1515 - accuracy: 0.9473 - val_loss: 0.3250 - val_accuracy: 0.8860
Epoch 95/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1667 - accuracy: 0.9341 - val_loss: 0.1614 - val_accuracy: 0.9561
Epoch 96/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2082 - accuracy: 0.9099 - val_loss: 0.2350 - val_accuracy: 0.8596
Epoch 97/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1607 - accuracy: 0.9473 - val_loss: 0.1731 - val_accuracy: 0.9211
Epoch 98/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1848 - accuracy: 0.9297 - val_loss: 0.1893 - val_accuracy: 0.9474
Epoch 99/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1423 - accuracy: 0.9429 - val_loss: 0.2003 - val_accuracy: 0.9386
Epoch 100/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1546 - accuracy: 0.9275 - val_loss: 0.1564 - val_accuracy: 0.9386
Epoch 101/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1660 - accuracy: 0.9385 - val_loss: 0.3115 - val_accuracy: 0.8421
Epoch 102/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1687 - accuracy: 0.9253 - val_loss: 0.1773 - val_accuracy: 0.9474
Epoch 103/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1407 - accuracy: 0.9363 - val_loss: 0.1558 - val_accuracy: 0.9474
Epoch 104/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1471 - accuracy: 0.9385 - val_loss: 0.1535 - val_accuracy: 0.9561
Epoch 105/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1416 - accuracy: 0.9341 - val_loss: 0.1589 - val_accuracy: 0.9474
Epoch 106/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1495 - accuracy: 0.9341 - val_loss: 0.1601 - val_accuracy: 0.9211
Epoch 107/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1536 - accuracy: 0.9275 - val_loss: 0.1517 - val_accuracy: 0.9649
Epoch 108/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1517 - accuracy: 0.9341 - val_loss: 0.1558 - val_accuracy: 0.9561
Epoch 109/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2463 - accuracy: 0.9121 - val_loss: 0.1751 - val_accuracy: 0.9561
Epoch 110/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1712 - accuracy: 0.9363 - val_loss: 0.1651 - val_accuracy: 0.9474
Epoch 111/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1500 - accuracy: 0.9341 - val_loss: 0.1724 - val_accuracy: 0.8947
Epoch 112/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1552 - accuracy: 0.9319 - val_loss: 0.1775 - val_accuracy: 0.9474
Epoch 113/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1418 - accuracy: 0.9363 - val_loss: 0.1526 - val_accuracy: 0.9474
Epoch 114/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1419 - accuracy: 0.9385 - val_loss: 0.1803 - val_accuracy: 0.9386
Epoch 115/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1397 - accuracy: 0.9385 - val_loss: 0.1477 - val_accuracy: 0.9474
Epoch 116/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1666 - accuracy: 0.9231 - val_loss: 0.1580 - val_accuracy: 0.9386
Epoch 117/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1318 - accuracy: 0.9407 - val_loss: 0.1577 - val_accuracy: 0.9386
Epoch 118/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1624 - accuracy: 0.9429 - val_loss: 0.1346 - val_accuracy: 0.9561
Epoch 119/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1397 - accuracy: 0.9363 - val_loss: 0.1319 - val_accuracy: 0.9649
Epoch 120/400
57/57 [==============================] - 0s 3ms/step - loss: 0.2033 - accuracy: 0.9231 - val_loss: 0.1475 - val_accuracy: 0.9474
Epoch 121/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1925 - accuracy: 0.9231 - val_loss: 0.1861 - val_accuracy: 0.9474
Epoch 122/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1617 - accuracy: 0.9275 - val_loss: 0.1610 - val_accuracy: 0.9386
Epoch 123/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1414 - accuracy: 0.9385 - val_loss: 0.1381 - val_accuracy: 0.9474
Epoch 124/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1351 - accuracy: 0.9341 - val_loss: 0.1730 - val_accuracy: 0.9561
Epoch 125/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1518 - accuracy: 0.9341 - val_loss: 0.1384 - val_accuracy: 0.9649
Epoch 126/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1496 - accuracy: 0.9407 - val_loss: 0.1305 - val_accuracy: 0.9561
Epoch 127/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1342 - accuracy: 0.9429 - val_loss: 0.1533 - val_accuracy: 0.9298
Epoch 128/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1512 - accuracy: 0.9297 - val_loss: 0.1804 - val_accuracy: 0.9474
Epoch 129/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1281 - accuracy: 0.9495 - val_loss: 0.1807 - val_accuracy: 0.8947
Epoch 130/400
57/57 [==============================] - 0s 6ms/step - loss: 0.1522 - accuracy: 0.9363 - val_loss: 0.1676 - val_accuracy: 0.9211
Epoch 131/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1367 - accuracy: 0.9363 - val_loss: 0.1800 - val_accuracy: 0.9561
Epoch 132/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1307 - accuracy: 0.9385 - val_loss: 0.1769 - val_accuracy: 0.8947
Epoch 133/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1419 - accuracy: 0.9495 - val_loss: 0.1509 - val_accuracy: 0.9474
Epoch 134/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1266 - accuracy: 0.9451 - val_loss: 0.1743 - val_accuracy: 0.9123
Epoch 135/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1187 - accuracy: 0.9451 - val_loss: 0.1365 - val_accuracy: 0.9386
Epoch 136/400
57/57 [==============================] - 0s 6ms/step - loss: 0.1258 - accuracy: 0.9495 - val_loss: 0.1278 - val_accuracy: 0.9561
Epoch 137/400
57/57 [==============================] - 0s 5ms/step - loss: 0.1265 - accuracy: 0.9516 - val_loss: 0.1303 - val_accuracy: 0.9386
Epoch 138/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1246 - accuracy: 0.9582 - val_loss: 0.1460 - val_accuracy: 0.9561
Epoch 139/400
57/57 [==============================] - 0s 4ms/step - loss: 0.1216 - accuracy: 0.9560 - val_loss: 0.1272 - val_accuracy: 0.9561
Epoch 140/400
57/57 [==============================] - 0s 3ms/step - loss: 0.1268 - accuracy: 0.9385 - val_loss: 0.1192 - val_accuracy: 0.9386
Epoch 141/400

In [ ]:
y_pred=classification_model.predict(x_test)

4/4 [==============================] - 0s 3ms/step

In [ ]:
y_pred

array([[9.2409587e-01],
       [2.0779429e-03],
       [2.6902386e-05],
       [3.5556180e-03],
       [4.7239242e-05],
       [2.7082833e-06],
       [4.1198850e-06],
       [3.9547254e-07],
       [1.8276566e-03],
       [3.4617906e-07],
       [3.5489779e-02],
       [1.9628881e-02],
       [1.3356954e-06],
       [4.5415249e-01],
       [6.0140938e-03],
       [4.8122203e-01],
       [6.8501820e-04],
       [9.9999946e-01],
       [9.9973851e-01],
       [9.9999988e-01],
       [9.9999988e-01],
       [2.2138216e-01],
       [2.3194984e-06],
       [6.0138762e-05],
       [9.9611008e-01],
       [7.7702578e-05],
       [2.4679957e-06],
       [1.5816191e-01],
       [5.6611025e-06],
       [1.0000000e+00],
       [8.1286707e-06],
       [9.9996144e-01],
       [3.3855110e-03],
       [9.2524636e-01],
       [1.2098941e-07],
       [9.9999088e-01],
       [3.5738421e-04],
       [9.7546315e-01],
       [4.7534191e-05],
       [9.6641201e-01],
       [3.8772684e-01],
       [1.9691016e-04],
       [8.8127005e-01],
       [9.4174176e-08],
       [3.1298050e-01],
       [9.9999976e-01],
       [5.3722476e-07],
       [9.3963271e-04],
       [2.5333143e-06],
       [9.9948609e-01],
       [9.9840254e-01],
       [5.5971455e-02],
       [9.9983835e-01],
       [1.1008897e-06],
       [2.0553204e-04],
       [1.5479181e-07],
       [6.6760022e-06],
       [2.0152878e-02],
       [1.8800705e-04],
       [1.0000000e+00],
       [5.0933135e-01],
       [8.7968695e-01],
       [4.1744643e-06],
       [4.8142661e-05],
       [9.9936831e-01],
       [1.5857323e-01],
       [1.0000000e+00],
       [9.9999958e-01],
       [9.9977064e-01],
       [4.4985143e-05],
       [4.1091386e-02],
       [9.9994761e-01],
       [3.7467451e-06],
       [3.1621176e-01],
       [9.9832630e-01],
       [1.5015304e-03],
       [8.5859631e-07],
       [1.3599510e-04],
       [6.3252119e-05],
       [7.4643543e-04],
       [8.2434863e-01],
       [9.9997813e-01],
       [9.9997139e-01],
       [3.2791711e-05],
       [3.1467125e-01],
       [1.4350186e-06],
       [1.1592103e-06],
       [1.0921246e-06],
       [9.9935156e-01],
       [1.0000000e+00],
       [4.3975786e-07],
       [2.5285116e-01],
       [5.8523864e-02],
       [9.9633253e-01],
       [7.1926840e-04],
       [4.6099690e-06],
       [1.0000000e+00],
       [4.6862150e-04],
       [1.8331624e-04],
       [5.3054839e-05],
       [9.3040944e-06],
       [4.4920316e-06],
       [2.9963866e-04],
       [5.5456866e-02],
       [9.9922580e-01],
       [3.1497264e-06],
       [9.6656632e-01],
       [3.3640938e-03],
       [2.5285116e-01],
       [9.9466407e-01],
       [2.2951109e-04],
       [9.4101286e-01],
       [9.8509294e-01],
       [4.1124411e-04]], dtype=float32)