<a href="https://colab.research.google.com/github/sarathkurapati/ml-dl-notebooks/blob/main/Medical_Insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [207]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as sns

In [208]:
df=pd.read_csv("/content/Medical_insurance.csv")

In [209]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [210]:
df.drop(columns=["age","sex","children"],axis=1,inplace=True)

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   bmi      2772 non-null   float64
 1   smoker   2772 non-null   object
 2   region   2772 non-null   object
 3   charges  2772 non-null   float64
dtypes: float64(2), object(2)
memory usage: 86.8+ KB

In [212]:
df.describe()

               bmi       charges
count  2772.000000   2772.000000
mean     30.701349  13261.369959
std       6.129449  12151.768945
min      15.960000   1121.873900
25%      26.220000   4687.797000
50%      30.447500   9333.014350
75%      34.770000  16577.779500
max      53.130000  63770.428010

In [213]:
df.isnull().sum()

bmi        0
smoker     0
region     0
charges    0
dtype: int64

In [214]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["smoker"]=le.fit_transform(df["smoker"])
df["region"]=le.fit_transform(df["region"])

In [215]:
df.head()

      bmi  smoker  region      charges
0  27.900       1       3  16884.92400
1  33.770       0       2   1725.55230
2  33.000       0       2   4449.46200
3  22.705       0       1  21984.47061
4  28.880       0       1   3866.85520

In [216]:
x=df.drop(columns="charges",axis=1)
x.head()

      bmi  smoker  region
0  27.900       1       3
1  33.770       0       2
2  33.000       0       2
3  22.705       0       1
4  28.880       0       1

In [217]:
y=df[["charges"]]
y.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [218]:
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
x_scaled=pd.DataFrame(scale.fit_transform(x),columns = x.columns)
y_scaled= pd.DataFrame(scale.fit_transform(y),columns = y.columns)

In [219]:
x_scaled

           bmi  smoker    region
0     0.321227     1.0  1.000000
1     0.479150     0.0  0.666667
2     0.458434     0.0  0.666667
3     0.181464     0.0  0.333333
4     0.347592     0.0  0.333333
...        ...     ...       ...
2767  0.789884     0.0  0.666667
2768  0.501480     0.0  1.000000
2769  0.270917     1.0  0.333333
2770  0.074119     0.0  0.333333
2771  0.420769     0.0  1.000000

[2772 rows x 3 columns]

In [220]:
y_scaled

       charges
0     0.251611
1     0.009636
2     0.053115
3     0.333010
4     0.043816
...        ...
2767  0.118885
2768  0.014339
2769  0.244683
2770  0.326799
2771  0.139326

[2772 rows x 1 columns]

In [221]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [222]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((1940, 3), (832, 3), (1940, 1), (832, 1))

LINEAR REGRESSION

In [223]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(xtrain,ytrain)

LinearRegression()

In [224]:
y_pred=lm.predict(xtest)

In [225]:
from sklearn.metrics import r2_score
score=r2_score(y_pred,ytest)
#MEAN SQUARD ERROR
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ytest, y_pred)
print('Mean Squared Error:', mse)
#ROOT MEAN SQUARED ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ytest, y_pred)
rmse = np.sqrt(mse)
print('Root Mean Squared Error:', rmse)
#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(ytest, y_pred)
print('Mean Absolute Error:', mae)
print("r2_score:",score)

Mean Squared Error: 53943168.45169342
Root Mean Squared Error: 7344.601313324872
Mean Absolute Error: 5532.744145224219
r2_score: 0.4267138919685921

ANN

In [226]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [227]:
reg_model=Sequential()
#Adding the input layer
reg_model.add(Dense(3,activation="relu"))
#Adding four hidden layers
reg_model.add(Dense(128,activation="relu"))
reg_model.add(Dense(64,activation="relu"))
reg_model.add(Dense(32,activation="relu"))
reg_model.add(Dense(16,activation="relu"))
#Adding the output layer
reg_model.add(Dense(1,activation="linear"))

In [228]:
reg_model.compile(optimizer="adam",loss="mse",metrics=['mse','mae'])

In [229]:
reg_model.fit(xtrain,ytrain,epochs=10,batch_size=10,validation_data=(xtest,ytest))

Epoch 1/10
194/194 [==============================] - 2s 4ms/step - loss: 249509168.0000 - mse: 249509168.0000 - mae: 11358.4639 - val_loss: 148183200.0000 - val_mse: 148183200.0000 - val_mae: 9646.1689
Epoch 2/10
194/194 [==============================] - 1s 3ms/step - loss: 138053648.0000 - mse: 138053648.0000 - mae: 9092.1924 - val_loss: 147217600.0000 - val_mse: 147217600.0000 - val_mae: 9666.2695
Epoch 3/10
194/194 [==============================] - 1s 3ms/step - loss: 135727824.0000 - mse: 135727824.0000 - mae: 9171.4336 - val_loss: 147827424.0000 - val_mse: 147827424.0000 - val_mae: 8737.4199
Epoch 4/10
194/194 [==============================] - 1s 3ms/step - loss: 134830848.0000 - mse: 134830848.0000 - mae: 8990.7637 - val_loss: 144244192.0000 - val_mse: 144244192.0000 - val_mae: 9403.7178
Epoch 5/10
194/194 [==============================] - 1s 3ms/step - loss: 134095752.0000 - mse: 134095752.0000 - mae: 9026.4961 - val_loss: 142987792.0000 - val_mse: 142987792.0000 - val_mae: 9028.8350
Epoch 6/10
194/194 [==============================] - 1s 3ms/step - loss: 133022592.0000 - mse: 133022592.0000 - mae: 9006.7422 - val_loss: 141723200.0000 - val_mse: 141723200.0000 - val_mae: 9282.3027
Epoch 7/10
194/194 [==============================] - 1s 6ms/step - loss: 131652640.0000 - mse: 131652640.0000 - mae: 8942.5527 - val_loss: 140213232.0000 - val_mse: 140213232.0000 - val_mae: 9154.2969
Epoch 8/10
194/194 [==============================] - 1s 6ms/step - loss: 130730376.0000 - mse: 130730376.0000 - mae: 8977.5703 - val_loss: 139157888.0000 - val_mse: 139157888.0000 - val_mae: 8821.4395
Epoch 9/10
194/194 [==============================] - 1s 4ms/step - loss: 128518048.0000 - mse: 128518048.0000 - mae: 8841.5420 - val_loss: 137431280.0000 - val_mse: 137431280.0000 - val_mae: 8756.6006
Epoch 10/10
194/194 [==============================] - 1s 3ms/step - loss: 126303008.0000 - mse: 126303008.0000 - mae: 8827.5664 - val_loss: 134642480.0000 - val_mse: 134642480.0000 - val_mae: 9086.2959

In [230]:
y_pred_1=reg_model.predict(xtest)

26/26 [==============================] - 0s 2ms/step

In [231]:
# Evaluate the model on test data using MSE
from tensorflow import keras
#MEAN SQUARD ERROR
from sklearn.metrics import mean_squared_error
mse_1 = mean_squared_error(ytest, y_pred)
print('Mean Squared Error:', mse_1)
#ROOT MEAN SQUARED ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
mse_1 = mean_squared_error(ytest, y_pred)
rmse_1 = np.sqrt(mse_1)
print('Root Mean Squared Error:', rmse_1)
#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae_1 = mean_absolute_error(ytest, y_pred)
print('Mean Absolute Error:', mae_1)
from sklearn.metrics import r2_score
r2score_1=r2_score(y_pred,ytest)
print("r2score:",r2score_1)

Mean Squared Error: 53943168.45169342
Root Mean Squared Error: 7344.601313324872
Mean Absolute Error: 5532.744145224219
r2score: 0.4267138919685921

In [232]:
df.head()

      bmi  smoker  region      charges
0  27.900       1       3  16884.92400
1  33.770       0       2   1725.55230
2  33.000       0       2   4449.46200
3  22.705       0       1  21984.47061
4  28.880       0       1   3866.85520

In [233]:
Testing=reg_model.predict([[28.880,0,1]])
Testing

1/1 [==============================] - 0s 131ms/step

array([[12973.67]], dtype=float32)

RANDOM FOREST

In [234]:
#Random forest regressor
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(xtrain,ytrain)

<ipython-input-234-c84bfaa9c6dc>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(xtrain,ytrain)

RandomForestRegressor()

In [235]:
y_pred_2=rf.predict(xtest)
#MEAN SQUARD ERROR
from sklearn.metrics import mean_squared_error
mse_2 = mean_squared_error(ytest, y_pred_2)
print('Mean Squared Error:', mse_2)
#ROOT MEAN SQUARED ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
mse_2= mean_squared_error(ytest, y_pred_2)
rmse_2 = np.sqrt(mse_2)
print('Root Mean Squared Error:', rmse_2)
#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae_2 = mean_absolute_error(ytest, y_pred_2)
print('Mean Absolute Error:', mae_2)
from sklearn.metrics import r2_score
r2score_2=r2_score(y_pred,ytest)
print("r2score:",r2score_2)

Mean Squared Error: 28695726.51667358
Root Mean Squared Error: 5356.839228189846
Mean Absolute Error: 3792.41619494703
r2score: 0.4267138919685921

DECISION TREE REGRESSOR

In [236]:
#DECISION TREE REGRESSOR
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(xtrain, ytrain)
y_pred_3 = dt.predict(xtest)

#MEAN SQUARD ERROR
from sklearn.metrics import mean_squared_error
mse_3 = mean_squared_error(ytest, y_pred_3)
print('Mean Squared Error:', mse_3)
#ROOT MEAN SQUARED ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
mse_3= mean_squared_error(ytest, y_pred_3)
rmse_3 = np.sqrt(mse_3)
print('Root Mean Squared Error:', rmse_3)
#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae_3 = mean_absolute_error(ytest, y_pred_3)
print('Mean Absolute Error:', mae_3)
from sklearn.metrics import r2_score
r2score_3=r2_score(y_pred,ytest)
print("r2score:",r2score_3)

Mean Squared Error: 30346402.393593773
Root Mean Squared Error: 5508.756882781611
Mean Absolute Error: 3422.9380307184333
r2score: 0.4267138919685921

XG BOOST

In [237]:
#xg boost regressor
import xgboost as xgb
xgbr = xgb.XGBRegressor()
xgbr.fit(xtrain, ytrain)
y_pred_4= xgbr.predict(xtest)

#MEAN SQUARD ERROR
from sklearn.metrics import mean_squared_error
mse_4 = mean_squared_error(ytest, y_pred_4)
print('Mean Squared Error:', mse_4)
#ROOT MEAN SQUARED ERROR
import numpy as np
from sklearn.metrics import mean_squared_error
mse_4= mean_squared_error(ytest, y_pred_4)
rmse_4 = np.sqrt(mse_4)
print('Root Mean Squared Error:', rmse_4)
#MEAN ABSOLUTE ERROR
from sklearn.metrics import mean_absolute_error
mae_4= mean_absolute_error(ytest, y_pred_4)
print('Mean Absolute Error:', mae_4)
from sklearn.metrics import r2_score
r2score_4=r2_score(y_pred,ytest)
print("r2score:",r2score_4)

Mean Squared Error: 28771481.200410962
Root Mean Squared Error: 5363.905405617344
Mean Absolute Error: 3671.277121882888
r2score: 0.4267138919685921